### ISSUE TITLE
nearbyLocalAddress.address must not be null exception

### ISSUE THREAD

**Issue by xiaonanstudio** [android/connectivity-samples#285]
When i use the UwbRanging sample, it always crash.
I tested the sample with two Pixel 6 Pro mobiles (Android version: 13, TQ1A.230105.002), one for Controlee and the other one for Controller.

#1 com.google.android.gms.nearby.connection.ConnectionLifecycleCallback#onConnectionInitiated()
#2 com.google.android.gms.nearby.connection.ConnectionsClient#acceptConnection()
#3 com.google.android.gms.nearby.connection.ConnectionLifecycleCallback#onConnectionResult()
#4 androidx.core.uwb.UwbManager#controleeSessionScope() - crashed here

FATAL EXCEPTION: DefaultDispatcher-worker-5
Process: com.google.apps.hellouwb, PID: 9822
java.lang.NullPointerException: nearbyLocalAddress.address must not be null
    at androidx.core.uwb.impl.UwbManagerImpl.createClientSessionScope(UwbManagerImpl.kt:54)
    at androidx.core.uwb.impl.UwbManagerImpl.access$createClientSessionScope(UwbManagerImpl.kt:33)
    at androidx.core.uwb.impl.UwbManagerImpl$createClientSessionScope$1.invokeSuspend(Unknown Source:15)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
    Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@abcc459, Dispatchers.IO]
Sending signal. PID: 9822 SIG: 9

**Comment by zidaliu** [comment]
Meet the same problem :) I have two pixel 6 pros, however, one works well and another doesn't work.

**Comment by zidaliu** [comment]
I meet the same problem, however, when I restart the phone, the problem is fixed

**Comment by chinesco** [comment]
This should have been resolved by now, if not please file a bug here:
https://issuetracker.google.com/issues/new?component=1185313&template=1680952

**Comment by hzhou3** [comment]
@zidaliu @xiaonanstudio Hi there, does this sample work anymore? It seems my phones (Samsung s21+, pixel 7 pro) cannot see each other... Any advice would be greatly appreciated. Thanks!

**Comment by xiaonanstudio** [comment]
> @zidaliu @xiaonanstudio Hi there, does this sample work anymore? It seems my phones (Samsung s21+, pixel 7 pro) cannot see each other... Any advice would be greatly appreciated. Thanks!

Yes, it works, i tested on Pixel 6 Pro, Samsung Galaxy S23 Ultra.
Please login to the Google account on Google Play Store, and upgrade the Google Play Store app, then reboot your mobile phone and try again.

**Comment by hzhou3** [comment]
> > @zidaliu @xiaonanstudio Hi there, does this sample work anymore? It seems my phones (Samsung s21+, pixel 7 pro) cannot see each other... Any advice would be greatly appreciated. Thanks!
> 
> Yes, it works, i tested on Pixel 6 Pro, Samsung Galaxy S23 Ultra. Please login to the Google account on Google Play Store, and upgrade the google applications in your mobile phone, then reboot your mobile phone and try again.



Hi, thanks for replying! I have updated google play services. And I can see now the phones are able to see each other. However, the graph is still not showing anything... Did you change any of the sample code? If so, do you mind sharing the code? Thanks in advance!
